project_id = "hrkptgopdvwpquhffrew"

[functions.send-activation-email]
verify_jwt = false

[functions.send-resend-email]
verify_jwt = false

[functions.create-seed-auth-users]
verify_jwt = false

[functions.cleanup-dummy-data]
verify_jwt = false