// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrkptgopdvwpquhffrew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhya3B0Z29wZHZ3cHF1aGZmcmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTMyNTcsImV4cCI6MjA3MjUyOTI1N30.FcYva7ub1jlgfkIKpA4CoG3m6jsmBIUNcz47jeKrEzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});