// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwfwmbaiiznbcgwxlnbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZndtYmFpaXpuYmNnd3hsbmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjIzNjgsImV4cCI6MjA3MjMzODM2OH0.FUG6HSyXnwDs7G1jUITX819CMYYwPqc_HQmmrJJ7T0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});